name: Performance Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-k6-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install K6
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg software-properties-common
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/etc/apt/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Run K6 Response Time Test
        env:
          API_URL: ${{ secrets.API_URL }}
          USER_ROLE: ${{ secrets.USER_ROLE }}
          JWT_TOKEN: ${{ secrets.JWT_TOKEN }}
        run: k6 run k6/scripts/response-time-test.js

      - name: Run K6 Stress Test
        env:
          API_URL: ${{ secrets.API_URL }}
          USER_ROLE: ${{ secrets.USER_ROLE }}
          JWT_TOKEN: ${{ secrets.JWT_TOKEN }}
        run: k6 run k6/scripts/stress-test.js
